const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.Mouse,
		C3.Plugins.Function,
		C3.Plugins.Browser,
		C3.Plugins.video,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.TextBox,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Acts.SetSource,
		C3.Plugins.video.Acts.SetLooping,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Browser.Acts.ConsoleLog
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{TiledBackground: 0},
	{buttonX: 0},
	{buttonY: 0},
	{LiteTween: 0},
	{btnMenu: 0},
	{btnInfo: 0},
	{btnSound: 0},
	{Mouse: 0},
	{bgPopup: 0},
	{positionX: 0},
	{positionY: 0},
	{LitePopOpen: 0},
	{LitePopClose: 0},
	{popupInfo: 0},
	{Function: 0},
	{btnHome: 0},
	{btnPopPrev: 0},
	{btnPopNext: 0},
	{Sprite6: 0},
	{btnClose: 0},
	{btnPerangkat: 0},
	{btnLatihan: 0},
	{btnGlosariu: 0},
	{btnMateri: 0},
	{btnGame: 0},
	{btnPenulis: 0},
	{Browser: 0},
	{bgPopupClose: 0},
	{popupClose: 0},
	{btnTidakClose: 0},
	{btnYaClose: 0},
	{perangkatPopup: 0},
	{btnDownPerangkat: 0},
	{btnUpPerangkat: 0},
	{videoPerangkat: 0},
	{btnClosePerangkat: 0},
	{bgCreator: 0},
	{btnHomeMenu: 0},
	{bgGlosarium: 0},
	{btnNextGlosarium: 0},
	{btnPrevGlosarium: 0},
	{btnCloseGlosarium: 0},
	{bgMenu: 0},
	{bgMateri: 0},
	{btnLetStudy: 0},
	{materiStudy: 0},
	{btnNextMateri: 0},
	{btnPrevMateri: 0},
	{videoMateri: 0},
	{btnUangRupiah: 0},
	{btnSetaraBanding: 0},
	{btnOperasiDasar: 0},
	{btnSoalCerita: 0},
	{txtDebug: 0},
	{materi500: 0},
	{materi1k: 0},
	{materi2k: 0},
	{materi5k: 0},
	{materi10k: 0},
	{materi20k: 0},
	{materi50k: 0},
	{materi100k: 0},
	{btnBackMateri: 0},
	{materiUang: 0},
	{btnSearchSetara: 0},
	{materiSetara: 0},
	{bgLatihan: 0},
	{Sprite3: 0},
	{example: 0},
	{inframe: 0},
	{btnLatihanSoal: 0},
	{bgLatihanSoal: 0},
	{Sprite: 0},
	{txtTitle: 0},
	{showLatihan: 0},
	{pictCoupon: 0},
	{txtQtyCoupon: 0},
	{jawaban: 0},
	{ada: 0},
	{slotJawaban: 0},
	{pilihan: 0},
	{sizeX: 0},
	{sizeY: 0},
	{DragDrop: 0},
	{LitePosition: 0},
	{pilihanSoal: 0},
	{bgYakin: 0},
	{btnNoYakin: 0},
	{btnYesYakin: 0},
	{bgBenarSalah: 0},
	{btnNextSoal: 0},
	{pictUang: 0},
	{tarikGaris: 0},
	{endGaris: 0},
	{viewKupon: 0},
	{soalLatihan2: 0},
	{jawabSoalA2: 0},
	{jawabSoalB2: 0},
	{jawabSoalC2: 0},
	{Sprite2: 0},
	{jawabSoalD2: 0},
	{jawabSoalA3: 0},
	{jawabSoalB3: 0},
	{jawabSoalC3: 0},
	{jawabSoalD3: 0},
	{jawabSoalA4: 0},
	{jawabSoalB4: 0},
	{jawabSoalC4: 0},
	{jawabSoalD4: 0},
	{Sprite4: 0},
	{pilihSoalA4: 0},
	{pilihSoalB4: 0},
	{pilihSoalC4: 0},
	{pilihSoalD4: 0},
	{bgSoal5: 0},
	{inputNominal: 0},
	{Text: 0},
	{Keyboard: 0},
	{Sprite5: 0},
	{btnPlayGame: 0},
	{game_1: 0},
	{btnNoteBelanja: 0},
	{btnPriceList: 0},
	{nilai: 0},
	{heart: 0},
	{Tilemap: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{name: 0},
	{price: 0},
	{key: 0},
	{qty: 0},
	{soal: 0},
	{cartMakanan: 0},
	{nextMarket: 0},
	{Sprite9: 0},
	{noteCart: 0},
	{prevMarket: 0},
	{Sprite11: 0},
	{cekMarket: 0},
	{cartSayuran: 0},
	{Sprite12: 0},
	{btnSaveCart: 0},
	{btnPlusCart: 0},
	{btnMinCart: 0},
	{txtQtyCart: 0},
	{end_game1: 0},
	{txtInputBayar: 0},
	{bgBenar: 0},
	{btnNextGame: 0},
	{bgSalah: 0},
	{btnBackGame: 0},
	{slotJawab: 0},
	{hasilSoal: 0},
	{jawabanSoal: 0},
	{valueCoupon: 0},
	{soal2: 0},
	{jawabanSoal2: 0},
	{jawabanSoal3: 0},
	{soal4: 0},
	{jawabanSoal4: 0},
	{soal5: 0},
	{jawabanSoal5: 0},
	{statusPopup: 0},
	{popup: 0},
	{backsound: 0},
	{glosarium: 0},
	{latihan1: 0},
	{latihan2: 0},
	{latihan3: 0},
	{latihan4: 0},
	{latihan5: 0},
	{coupon: 0},
	{kerjakanSoal: 0},
	{letsPlay: 0},
	{minMateri: 0},
	{maxMateri: 0},
	{buttonMateri: 0},
	{materi: 0},
	{perangkat: 0},
	{game: 0},
	{jumlahBarang: 0},
	{belanjaStatus: 0},
	{belanjaKey: 0},
	{soalBelanja: 0},
	{totalBelanja: 0},
	{playerAnswer: 0},
	{jawabanGame: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnInfo: class extends self.ISpriteInstance {},
	btnSound: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	bgPopup: class extends self.ISpriteInstance {},
	popupInfo: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnPopPrev: class extends self.ISpriteInstance {},
	btnPopNext: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnPerangkat: class extends self.ISpriteInstance {},
	btnLatihan: class extends self.ISpriteInstance {},
	btnGlosariu: class extends self.ISpriteInstance {},
	btnMateri: class extends self.ISpriteInstance {},
	btnGame: class extends self.ISpriteInstance {},
	btnPenulis: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	bgPopupClose: class extends self.ISpriteInstance {},
	popupClose: class extends self.ISpriteInstance {},
	btnTidakClose: class extends self.ISpriteInstance {},
	btnYaClose: class extends self.ISpriteInstance {},
	perangkatPopup: class extends self.ISpriteInstance {},
	btnDownPerangkat: class extends self.ISpriteInstance {},
	btnUpPerangkat: class extends self.ISpriteInstance {},
	videoPerangkat: class extends self.IWorldInstance {},
	btnClosePerangkat: class extends self.ISpriteInstance {},
	bgCreator: class extends self.ISpriteInstance {},
	btnHomeMenu: class extends self.ISpriteInstance {},
	bgGlosarium: class extends self.ISpriteInstance {},
	btnNextGlosarium: class extends self.ISpriteInstance {},
	btnPrevGlosarium: class extends self.ISpriteInstance {},
	btnCloseGlosarium: class extends self.ISpriteInstance {},
	bgMenu: class extends self.ISpriteInstance {},
	bgMateri: class extends self.ISpriteInstance {},
	btnLetStudy: class extends self.ISpriteInstance {},
	materiStudy: class extends self.ISpriteInstance {},
	btnNextMateri: class extends self.ISpriteInstance {},
	btnPrevMateri: class extends self.ISpriteInstance {},
	videoMateri: class extends self.IWorldInstance {},
	btnUangRupiah: class extends self.ISpriteInstance {},
	btnSetaraBanding: class extends self.ISpriteInstance {},
	btnOperasiDasar: class extends self.ISpriteInstance {},
	btnSoalCerita: class extends self.ISpriteInstance {},
	txtDebug: class extends self.ITextInstance {},
	materi500: class extends self.ISpriteInstance {},
	materi1k: class extends self.ISpriteInstance {},
	materi2k: class extends self.ISpriteInstance {},
	materi5k: class extends self.ISpriteInstance {},
	materi10k: class extends self.ISpriteInstance {},
	materi20k: class extends self.ISpriteInstance {},
	materi50k: class extends self.ISpriteInstance {},
	materi100k: class extends self.ISpriteInstance {},
	btnBackMateri: class extends self.ISpriteInstance {},
	materiUang: class extends self.ISpriteInstance {},
	btnSearchSetara: class extends self.ISpriteInstance {},
	materiSetara: class extends self.ISpriteInstance {},
	bgLatihan: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	example: class extends self.ISpriteInstance {},
	btnLatihanSoal: class extends self.ISpriteInstance {},
	bgLatihanSoal: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	txtTitle: class extends self.ITextInstance {},
	showLatihan: class extends self.ISpriteInstance {},
	pictCoupon: class extends self.ISpriteInstance {},
	txtQtyCoupon: class extends self.ITextInstance {},
	slotJawaban: class extends self.ISpriteInstance {},
	pilihanSoal: class extends self.ISpriteInstance {},
	bgYakin: class extends self.ISpriteInstance {},
	btnNoYakin: class extends self.ISpriteInstance {},
	btnYesYakin: class extends self.ISpriteInstance {},
	bgBenarSalah: class extends self.ISpriteInstance {},
	btnNextSoal: class extends self.ISpriteInstance {},
	pictUang: class extends self.ISpriteInstance {},
	tarikGaris: class extends self.ISpriteInstance {},
	endGaris: class extends self.ISpriteInstance {},
	viewKupon: class extends self.ISpriteInstance {},
	soalLatihan2: class extends self.ISpriteInstance {},
	jawabSoalA2: class extends self.ISpriteInstance {},
	jawabSoalB2: class extends self.ISpriteInstance {},
	jawabSoalC2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	jawabSoalD2: class extends self.ISpriteInstance {},
	jawabSoalA3: class extends self.ISpriteInstance {},
	jawabSoalB3: class extends self.ISpriteInstance {},
	jawabSoalC3: class extends self.ISpriteInstance {},
	jawabSoalD3: class extends self.ISpriteInstance {},
	jawabSoalA4: class extends self.ISpriteInstance {},
	jawabSoalB4: class extends self.ISpriteInstance {},
	jawabSoalC4: class extends self.ISpriteInstance {},
	jawabSoalD4: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	pilihSoalA4: class extends self.ISpriteInstance {},
	pilihSoalB4: class extends self.ISpriteInstance {},
	pilihSoalC4: class extends self.ISpriteInstance {},
	pilihSoalD4: class extends self.ISpriteInstance {},
	bgSoal5: class extends self.ISpriteInstance {},
	inputNominal: class extends self.ITextInputInstance {},
	Text: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	btnPlayGame: class extends self.ISpriteInstance {},
	game_1: class extends self.ISpriteInstance {},
	btnNoteBelanja: class extends self.ISpriteInstance {},
	btnPriceList: class extends self.ISpriteInstance {},
	heart: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	cartMakanan: class extends self.ISpriteInstance {},
	nextMarket: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	noteCart: class extends self.ISpriteInstance {},
	prevMarket: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	cekMarket: class extends self.ISpriteInstance {},
	cartSayuran: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	btnSaveCart: class extends self.ISpriteInstance {},
	btnPlusCart: class extends self.ISpriteInstance {},
	btnMinCart: class extends self.ISpriteInstance {},
	txtQtyCart: class extends self.ITextInstance {},
	end_game1: class extends self.ISpriteInstance {},
	txtInputBayar: class extends self.ITextInputInstance {},
	bgBenar: class extends self.ISpriteInstance {},
	btnNextGame: class extends self.ISpriteInstance {},
	bgSalah: class extends self.ISpriteInstance {},
	btnBackGame: class extends self.ISpriteInstance {}
}